name: Cypress E2E
on:
  push:
  pull_request:
jobs:
  basic-ubuntu-18-v10:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        # normally you would write
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run local
          wait-on: "http://localhost:8080"
