name: Widget CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v4.1.0
        with:
          build: npm run build
          start: npm run local
          wait-on: "http://localhost:8080"

      - name: Archive production build
        uses: actions/upload-artifact@v3
        with:
          name: Production bundle
          path: dist
