name: Widget CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run local
          wait-on: "http://localhost:8080"

      - name: Archive production build
        uses: actions/upload-artifact@v3
        with:
          name: Production bundle
          path: dist
